In [6]:
import pandas as pd
import sqlite3
import datetime

In [14]:
con = sqlite3.connect("C:/Users/mrunm/Documents/GitHub/Wildfire-and-Climate-Change/data/wildfires.sqlite")

In [15]:
pd.set_option('display.max_columns', 500)

In [16]:
fire = pd.read_sql_query("SELECT * from fires", con)
fire.head()

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,LOCAL_FIRE_REPORT_ID,LOCAL_INCIDENT_ID,FIRE_CODE,FIRE_NAME,ICS_209_INCIDENT_NUMBER,ICS_209_NAME,MTBS_ID,MTBS_FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME,Shape
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,1,PNF-47,BJ8K,FOUNTAIN,None,None,None,None,None,2005,2453403.5,33,1300,9.0,Miscellaneous,2453403.5,33.0,1730,0.10,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,13,13,AAC0,PIGEON,None,None,None,None,None,2004,2453137.5,133,0845,1.0,Lightning,2453137.5,133.0,1530,0.25,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,27,021,A32W,SLACK,None,None,None,None,None,2004,2453156.5,152,1921,5.0,Debris Burning,2453156.5,152.0,2024,0.10,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,43,6,None,DEER,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1400,0.10,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,44,7,None,STEVENOT,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1200,0.10,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [17]:
fire.describe()

,OBJECTID,FOD_ID,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,STAT_CAUSE_CODE,CONT_DATE,CONT_DOY,FIRE_SIZE,LATITUDE,LONGITUDE,OWNER_CODE
count,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06,9.889340e+05,988934.000000,1.880465e+06,1.880465e+06,1.880465e+06,1.880465e+06
mean,9.402330e+05,5.484020e+07,2.003710e+03,2.453064e+06,1.647191e+02,5.979037e+00,2.453238e+06,172.656766,7.452016e+01,3.678121e+01,-9.570494e+01,1.059658e+01
std,5.428436e+05,1.011963e+08,6.663099e+00,2.434573e+03,9.003891e+01,3.483860e+00,2.687548e+03,84.320348,2.497598e+03,6.139031e+00,1.671694e+01,4.404662e+00
min,1.000000e+00,1.000000e+00,1.992000e+03,2.448622e+06,1.000000e+00,1.000000e+00,2.448622e+06,1.000000,1.000000e-05,1.793972e+01,-1.788026e+02,0.000000e+00
25%,4.701170e+05,5.055000e+05,1.998000e+03,2.451084e+06,8.900000e+01,3.000000e+00,2.450701e+06,102.000000,1.000000e-01,3.281860e+01,-1.103635e+02,8.000000e+00
50%,9.402330e+05,1.067761e+06,2.004000e+03,2.453178e+06,1.640000e+02,5.000000e+00,2.453466e+06,181.000000,1.000000e+00,3.545250e+01,-9.204304e+01,1.400000e+01
75%,1.410349e+06,1.910639e+07,2.009000e+03,2.455036e+06,2.300000e+02,9.000000e+00,2.455754e+06,232.000000,3.300000e+00,4.082720e+01,-8.229760e+01,1.400000e+01
max,1.880465e+06,3.003484e+08,2.015000e+03,2.457388e+06,3.660000e+02,1.300000e+01,2.457392e+06,366.000000,6.069450e+05,7.033060e+01,-6.525694e+01,1.500000e+01

In [18]:
fire.shape

(1880465, 39)

In [19]:
wildfires_cleaned=fire[["SOURCE_REPORTING_UNIT_NAME","FIRE_NAME","FIRE_YEAR","DISCOVERY_DATE","DISCOVERY_DOY","STAT_CAUSE_DESCR","CONT_DATE","CONT_DOY","FIRE_SIZE","FIRE_SIZE_CLASS","LATITUDE","LONGITUDE","STATE","COUNTY","Shape"]]
wildfires_cleaned.head()

,SOURCE_REPORTING_UNIT_NAME,FIRE_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape
0,Plumas National Forest,FOUNTAIN,2005,2453403.5,33,Miscellaneous,2453403.5,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,Eldorado National Forest,PIGEON,2004,2453137.5,133,Lightning,2453137.5,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,Eldorado National Forest,SLACK,2004,2453156.5,152,Debris Burning,2453156.5,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,Eldorado National Forest,DEER,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,Eldorado National Forest,STEVENOT,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [20]:
fires = wildfires_cleaned.rename(columns={"SOURCE_REPORTING_UNIT_NAME":"UNIT_NAME", "STAT_CAUSE_DESCR":"CAUSE_DESCR","FIRE_SIZE_CLASS":"FIRE_CLASS"})
fires.head()

,UNIT_NAME,FIRE_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,CAUSE_DESCR,CONT_DATE,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape
0,Plumas National Forest,FOUNTAIN,2005,2453403.5,33,Miscellaneous,2453403.5,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,Eldorado National Forest,PIGEON,2004,2453137.5,133,Lightning,2453137.5,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,Eldorado National Forest,SLACK,2004,2453156.5,152,Debris Burning,2453156.5,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,Eldorado National Forest,DEER,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,Eldorado National Forest,STEVENOT,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [21]:
fires.shape

(1880465, 15)

In [22]:
print(fires.dtypes)

UNIT_NAME          object
FIRE_NAME          object
FIRE_YEAR           int64
DISCOVERY_DATE    float64
DISCOVERY_DOY       int64
CAUSE_DESCR        object
CONT_DATE         float64
CONT_DOY          float64
FIRE_SIZE         float64
FIRE_CLASS         object
LATITUDE          float64
LONGITUDE         float64
STATE              object
COUNTY             object
Shape              object
dtype: object

In [23]:
#Create a new function:
def num_missing(x):
    return sum(x.isnull())

#Applying per column:
print("Missing values per column:")
## Check how many are missing by column, and then check which ones have any missing values
print(fires.apply(num_missing, axis=0).where(lambda x : x != 0).dropna().head(20)) 
#axis=0 defines that function is to be applied on each column

Missing values per column:
FIRE_NAME    957189.0
CONT_DATE    891531.0
CONT_DOY     891531.0
COUNTY       678148.0
dtype: float64

In [24]:
#remove FIRE_NAME because it is not that important to name a fire and many obs are missing!
del fires ["FIRE_NAME"]

In [25]:
fires.head()

,UNIT_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,CAUSE_DESCR,CONT_DATE,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape
0,Plumas National Forest,2005,2453403.5,33,Miscellaneous,2453403.5,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1,Eldorado National Forest,2004,2453137.5,133,Lightning,2453137.5,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2,Eldorado National Forest,2004,2453156.5,152,Debris Burning,2453156.5,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [26]:
print(fires.apply(num_missing, axis=0).where(lambda x : x != 0).dropna().head(20))

CONT_DATE    891531.0
CONT_DOY     891531.0
COUNTY       678148.0
dtype: float64

In [27]:
#Julian Calendar conversion
fires['DISC_DATE'] = pd.to_datetime(fires['DISCOVERY_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
fires.head()

,UNIT_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,CAUSE_DESCR,CONT_DATE,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape,DISC_DATE
0,Plumas National Forest,2005,2453403.5,33,Miscellaneous,2453403.5,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...,2005-02-02
1,Eldorado National Forest,2004,2453137.5,133,Lightning,2453137.5,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...,2004-05-12
2,Eldorado National Forest,2004,2453156.5,152,Debris Burning,2453156.5,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...,2004-05-31
3,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...,2004-06-28
4,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...,2004-06-28

In [28]:
fires['CONTAIN_DATE'] = pd.to_datetime(fires['CONT_DATE'] - pd.Timestamp(0).to_julian_date(), unit='D')
fires.head()

,UNIT_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,CAUSE_DESCR,CONT_DATE,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape,DISC_DATE,CONTAIN_DATE
0,Plumas National Forest,2005,2453403.5,33,Miscellaneous,2453403.5,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...,2005-02-02,2005-02-02
1,Eldorado National Forest,2004,2453137.5,133,Lightning,2453137.5,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...,2004-05-12,2004-05-12
2,Eldorado National Forest,2004,2453156.5,152,Debris Burning,2453156.5,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...,2004-05-31,2004-05-31
3,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...,2004-06-28,2004-07-03
4,Eldorado National Forest,2004,2453184.5,180,Lightning,2453189.5,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...,2004-06-28,2004-07-03

In [29]:
del fires ["DISCOVERY_DATE"]
del fires ["CONT_DATE"]

In [30]:
#Deleted the Julian calendar columns for Discovery date and Contaned date which were converted to normal datetime format in DISC_DATE and CONTAIN_DATE
fires.head()

,UNIT_NAME,FIRE_YEAR,DISCOVERY_DOY,CAUSE_DESCR,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,COUNTY,Shape,DISC_DATE,CONTAIN_DATE
0,Plumas National Forest,2005,33,Miscellaneous,33.0,0.10,A,40.036944,-121.005833,CA,63,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...,2005-02-02,2005-02-02
1,Eldorado National Forest,2004,133,Lightning,133.0,0.25,A,38.933056,-120.404444,CA,61,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...,2004-05-12,2004-05-12
2,Eldorado National Forest,2004,152,Debris Burning,152.0,0.10,A,38.984167,-120.735556,CA,17,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...,2004-05-31,2004-05-31
3,Eldorado National Forest,2004,180,Lightning,185.0,0.10,A,38.559167,-119.913333,CA,3,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...,2004-06-28,2004-07-03
4,Eldorado National Forest,2004,180,Lightning,185.0,0.10,A,38.559167,-119.933056,CA,3,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...,2004-06-28,2004-07-03

In [31]:
#Missing values
#deleting the COUNTY column because of 37.7% missing values
del fires["COUNTY"]

In [32]:
print(fires.dtypes)

UNIT_NAME                object
FIRE_YEAR                 int64
DISCOVERY_DOY             int64
CAUSE_DESCR              object
CONT_DOY                float64
FIRE_SIZE               float64
FIRE_CLASS               object
LATITUDE                float64
LONGITUDE               float64
STATE                    object
Shape                    object
DISC_DATE        datetime64[ns]
CONTAIN_DATE     datetime64[ns]
dtype: object

In [33]:
fires.to_sql('wildfirecleaned', con, if_exists='replace', index=False)
pd.read_sql('select * from wildfirecleaned', con)

,UNIT_NAME,FIRE_YEAR,DISCOVERY_DOY,CAUSE_DESCR,CONT_DOY,FIRE_SIZE,FIRE_CLASS,LATITUDE,LONGITUDE,STATE,Shape,DISC_DATE,CONTAIN_DATE
0,Plumas National Forest,2005,33,Miscellaneous,33.0,0.10,A,40.036944,-121.005833,CA,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...,2005-02-02 00:00:00,2005-02-02 00:00:00
1,Eldorado National Forest,2004,133,Lightning,133.0,0.25,A,38.933056,-120.404444,CA,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...,2004-05-12 00:00:00,2004-05-12 00:00:00
2,Eldorado National Forest,2004,152,Debris Burning,152.0,0.10,A,38.984167,-120.735556,CA,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...,2004-05-31 00:00:00,2004-05-31 00:00:00
3,Eldorado National Forest,2004,180,Lightning,185.0,0.10,A,38.559167,-119.913333,CA,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...,2004-06-28 00:00:00,2004-07-03 00:00:00
4,Eldorado National Forest,2004,180,Lightning,185.0,0.10,A,38.559167,-119.933056,CA,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...,2004-06-28 00:00:00,2004-07-03 00:00:00
5,Eldorado National Forest,2004,182,Lightning,183.0,0.10,A,38.635278,-120.103611,CA,b'\x00\x01\xad\x10\x00\x00\xf0<~\x90\xa1\x06^\...,2004-06-30 00:00:00,2004-07-01 00:00:00
6,Eldorado National Forest,2004,183,Lightning,184.0,0.10,A,38.688333,-120.153333,CA,b'\x00\x01\xad\x10\x00\x00$o\x996\xd0\t^\xc0h\...,2004-07-01 00:00:00,2004-07-02 00:00:00
7,Shasta-Trinity National Forest,2005,67,Debris Burning,67.0,0.80,B,40.968056,-122.433889,CA,b'\x00\x01\xad\x10\x00\x00t)\xe8\xd5\xc4\x9b^\...,2005-03-08 00:00:00,2005-03-08 00:00:00
8,Shasta-Trinity National Forest,2005,74,Debris Burning,74.0,1.00,B,41.233611,-122.283333,CA,"b'\x00\x01\xad\x10\x00\x00\xdc\x8d\x1e""""\x92^\...",2005-03-15 00:00:00,2005-03-15 00:00:00
9,Eldorado National Forest,2004,183,Lightning,184.0,0.10,A,38.548333,-120.149167,CA,b'\x00\x01\xad\x10\x00\x00dS\\\xf2\x8b\t^\xc0\...,2004-07-01 00:00:00,2004-07-02 00:00:00
10,Eldorado National Forest,2004,184,Lightning,185.0,0.10,A,38.691667,-120.159722,CA,b'\x00\x01\xad\x10\x00\x00\x0c\xd6\x8b\xe38\n^...,2004-07-02 00:00:00,2004-07-03 00:00:00
11,Eldorado National Forest,2004,184,Lightning,185.0,0.10,A,38.527500,-120.106111,CA,b'\x00\x01\xad\x10\x00\x00L\xcc@\x86\xca\x06^\...,2004-07-02 00:00:00,2004-07-03 00:00:00
12,Eldorado National Forest,2004,247,Miscellaneous,247.0,0.10,A,38.786667,-120.193333,CA,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_\x0c^\...,2004-09-03 00:00:00,2004-09-03 00:00:00
13,Eldorado National Forest,2004,272,Campfire,272.0,6.00,B,38.433333,-120.510000,CA,b'\x00\x01\xad\x10\x00\x00p=\n\xd7\xa3 ^\xc0\x...,2004-09-28 00:00:00,2004-09-28 00:00:00
14,Eldorado National Forest,2004,277,Lightning,277.0,0.20,A,38.675833,-120.279722,CA,b'\x00\x01\xad\x10\x00\x00P\xb7\x06\xf8\xe6\x1...,2004-10-03 00:00:00,2004-10-03 00:00:00
15,Eldorado National Forest,2004,277,Lightning,277.0,0.10,A,38.564167,-120.542222,CA,"b'\x00\x01\xad\x10\x00\x00 \x84\xd3\xc4\xb3""^\...",2004-10-03 00:00:00,2004-10-03 00:00:00
16,Eldorado National Forest,2004,280,Equipment Use,295.0,16823.00,G,38.523333,-120.211667,CA,b'\x00\x01\xad\x10\x00\x00dS\\\xf2\x8b\r^\xc0\...,2004-10-06 00:00:00,2004-10-21 00:00:00
17,Eldorado National Forest,2004,287,Equipment Use,291.0,7700.00,G,38.780000,-120.260000,CA,b'\x00\x01\xad\x10\x00\x00p=\n\xd7\xa3\x10^\xc...,2004-10-13 00:00:00,2004-10-17 00:00:00
18,Eldorado National Forest,2004,325,Debris Burning,326.0,0.10,A,38.945000,-120.411667,CA,b'\x00\x01\xad\x10\x00\x004 )\xbfX\x1a^\xc00\\...,2004-11-20 00:00:00,2004-11-21 00:00:00
19,Lincoln National Forest,2004,156,Lightning,156.0,0.10,A,33.440833,-105.720556,NM,b'\x00\x01\xad\x10\x00\x00\xa8I\x11\x95\x1dnZ\...,2004-06-04 00:00:00,2004-06-04 00:00:00
20,Lincoln National Forest,2004,171,Lightning,171.0,0.10,A,33.307222,-105.628611,NM,b'\x00\x01\xad\x10\x00\x00\x88\xd6\x17*;hZ\xc0...,2004-06-19 00:00:00,2004-06-19 00:00:00
21,Lincoln National Forest,2004,173,Lightning,174.0,0.10,A,33.444444,-105.768056,NM,"b""\x00\x01\xad\x10\x00\x00|\xed\x81\xd2'qZ\xc0...",2004-06-21 00:00:00,2004-06-22 00:00:00
22,Lincoln National Forest,2004,177,Lightning,178.0,0.10,A,33.559444,-105.766111,NM,b'\x00\x01\xad\x10\x00\x00T\xa3\xe4\xf6\x07qZ\...,2004-06-25 00:00:00,2004-06-26 00:00:00
23,Lincoln National Forest,2004,183,Lightning,184.0,0.25,A,33.308056,-105.526111,NM,b'\x00\x01\xad\x10\x00\x00\xc8\xe0\xee\xcd\xab...,2004-07-01 00:00:00,2004-07-02 00:00:00
24,Lincoln National Forest,2004,183,Lightning,188.0,2.50,B,33.545278,-105.229444,NM,b'\x00\x01\xad\x10\x00\x00 \x83\xbb7\xafNZ\xc0...,2004-07-01 00:00:00,2004-07-06 00:00:00
25,Lincoln National Forest,2004,202,Lightning,202.0,10.00,C,33.315833,-105.512222,NM,b'\x00\x01\xad\x10\x00\x00\xcc\xcb\xb4?\xc8`Z\...,2004-07-20 00:00:00,2004-07-20 00:00:00
26,Lincoln National Forest,2004,78,Miscellaneous,78.0,8.20,B,33.444444,-105.631111,NM,b'\x00\x01\xad\x10\x00\x00\xe4e\xda\x1fdhZ\xc0...,2004-03-18 00:00:00,2004-03-18 00:00:00
27,Lincoln National Forest,2004,218,Lightning,218.0,0.10,A,33.368056,-105.507222,NM,b'\x00\x01\xad\x10\x00\x00\x14\xad/Tv`Z\xc0\xd...,2004-08-05 00:00:00,2004-08-05 00:00:00
28,Lincoln National Forest,2004,78,Debris Burning,78.0,0.25,A,33.385278,-105.638611,NM,"b'\x00\x01\xad\x10\x00\x00\xf8\x13""\x01\xdfhZ\...",2004-03-18 00:00:00,2004-03-18 00:00:00
29,Lincoln National Forest,2004,132,Debris Burning,132.0,0.25,A,33.382778,-105.700278,NM,b'\x00\x01\xad\x10\x00\x00\xc8\xcd\xe4Y\xd1lZ\...,2004-05-11 00:00:00,2004-05-11 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880435,Sonoma-Lake Napa Unit,2015,179,Miscellaneous,NaN,0.01,A,38.159780,-122.451750,CA,b'\x00\x01\xad\x10\x00\x00\xf0\xfd\xd4x\xe9\x9...,2015-06-28 00:00:00,None
1880436,Nevada-Yuba-Placer Unit,2015,80,Debris Burning,80.0,0.01,A,39.143821,-121.036533,CA,b'\x00\x01\xad\x10\x00\x00`\x0e\x82\x8eVB^\xc0...,2015-03-21 00:00:00,2015-03-21 00:00:00
1880437,Humboldt-Del Norte Unit,2015,131,Debris Burning,131.0,0.02,A,41.224483,-123.763317,CA,b'\x00\x01\xad\x10\x00\x00\xc4\xde\x8b/\xda\xf...,2015-05-11 00:00:00,2015-05-11 00:00:00
1880438,Nevada-Yuba-Placer Unit,2015,269,Miscellaneous,269.0,0.25,A,39.005712,-121.260759,CA,b'\x00\x01\xad\x10\x00\x00\xccH\x84F\xb0P^\xc0...,2015-09-26 00:00:00,2015-09-26 00:00:00
1880439,Kern County Fire Department,2015,27,Missing/Undefined,NaN,0.11,A,34.933333,-118.883333,CA,"b'\x00\x01\xad\x10\x00\x00\x90\x9e""\x87\x88\xb...",2015-01-27 00:00:00,None
1880440,Los Angeles County Fire Department,2015,185,Arson,NaN,0.11,A,34.716666,-118.800000,CA,b'\x00\x01\xad\x10\x00\x0003333\xb3]\xc0\xe0\x...,2015-07-04 00:00:00,None
1880441,Los Angeles County Fire Department,2015,341,Miscellaneous,NaN,11.00,C,34.450000,-118.583333,CA,b'\x00\x01\xad\x10\x00\x00\\k\xefSU\xa5]\xc0\x...,2015-12-07 00:00:00,None
1880442,San Mateo-Santa Cruz Unit,2015,87,Miscellaneous,87.0,1.00,B,37.090126,-122.074684,CA,b'\x00\x01\xad\x10\x00\x004bf\x9f\xc7\x84^\xc0...,2015-03-28 00:00:00,2015-03-28 00:00:00
1880443,Lassen-Modoc Unit,2015,270,Equipment Use,270.0,0.16,A,40.297000,-120.528000,CA,b'\x00\x01\xad\x10\x00\x00l\x12\x83\xc0\xca!^\...,2015-09-27 00:00:00,2015-09-27 00:00:00
1880444,Santa Clara Unit,2015,303,Miscellaneous,NaN,1.00,B,37.701111,-122.021111,CA,b'\x00\x01\xad\x10\x00\x00|\xa5\xf3\xe1Y\x81^\...,2015-10-30 00:00:00,None
1880445,CDF - San Bernardino Unit,2015,53,Missing/Undefined,NaN,0.10,A,37.361417,-118.465150,CA,b'\x00\x01\xad\x10\x00\x00\x00o\x81\x04\xc5\x9...,2015-02-22 00:00:00,None
1880446,CDF - San Bernardino Unit,2015,206,Arson,NaN,0.50,B,34.244444,-116.658889,CA,b'\x00\x01\xad\x10\x00\x00l\xac\xc4<+*]\xc0\x1...,2015-07-25 00:00:00,None
1880447,CDF - Monte Vista Unit,2015,28,Missing/Undefined,NaN,0.10,A,32.576754,-116.627539,CA,b'\x00\x01\xad\x10\x00\x00\xb8}V\x99)(]\xc00\x...,2015-01-28 00:00:00,None
1880448,Lassen-Modoc Unit,2015,177,Lightning,177.0,0.05,A,40.443000,-120.664433,CA,b'\x00\x01\xad\x10\x00\x00\x84X\xfd\x11\x86*^\...,2015-06-26 00:00:00,2015-06-26 00:00:00
1880449,Ventura County Fire Department,2015,239,Missing/Undefined,NaN,0.50,B,34.666666,-119.333333,CA,b'\x00\x01\xad\x10\x00\x00\\k\xefSU\xd5]\xc0\x...,2015-08-27 00:00:00,None
1880450,Santa Clara Unit,2015,178,Arson,NaN,0.10,A,38.041150,-121.985283,CA,b'\x00\x01\xad\x10\x00\x00\x80\x93m\xe0\x0e\x7...,2015-06-27 00:00:00,None
1880451,Amador-El Dorado Unit,2015,157,Equipment Use,157.0,1.00,B,38.644183,-120.863673,CA,b'\x00\x01\xad\x10\x00\x00\x08\\\x1ekF7^\xc0\x...,2015-06-06 00:00:00,2015-06-06 00:00:00
1880452,Los Angeles County Fire Department,2015,104,Debris Burning,NaN,0.12,A,34.163117,-118.693303,CA,b'\x00\x01\xad\x10\x00\x00\xf0A\t\x12_\xac]\xc...,2015-04-14 00:00:00,None
1880453,Los Angeles County Fire Department,2015,188,Children,NaN,0.12,A,34.278180,-118.621180,CA,b'\x00\x01\xad\x10\x00\x00h\x0c\xdfg\xc1\xa7]\...,2015-07-07 00:00:00,None
1880454,Tuolumne-Calaveras Unit,2015,255,Missing/Undefined,NaN,2.00,B,38.048577,-120.313090,CA,b'\x00\x01\xad\x10\x00\x00\x18\xad\xa3\xaa\t\x...,2015-09-12 00:00:00,None
1880455,Tuolumne-Calaveras Unit,2015,179,Miscellaneous,180.0,5.30,B,37.936253,-120.613743,CA,"b""\x00\x01\xad\x10\x00\x00\x84I\xb8\x90G'^\xc0...",2015-06-28 00:00:00,2015-06-29 00:00:00
1880456,Tehama-Glenn Unit,2015,165,Missing/Undefined,165.0,2.22,B,40.019907,-122.391398,CA,b'\x00\x01\xad\x10\x00\x00\x10n2\xaa\x0c\x99^\...,2015-06-14 00:00:00,2015-06-14 00:00:00
1880457,Shasta-Trinity Unit,2015,273,Arson,274.0,1.00,B,40.588583,-123.069617,CA,b'\x00\x01\xad\x10\x00\x00\xb8\x8f\xdc\x9at\xc...,2015-09-30 00:00:00,2015-10-01 00:00:00
1880458,Humboldt-Del Norte Unit,2015,213,Lightning,218.0,4.00,B,40.244833,-123.544167,CA,b'\x00\x01\xad\x10\x00\x00\xfc#\xd3\xa1\xd3\xe...,2015-08-01 00:00:00,2015-08-06 00:00:00
1880459,Sonoma-Lake Napa Unit,2015,148,Miscellaneous,148.0,0.50,B,38.415608,-122.660044,CA,b'\x00\x01\xad\x10\x00\x00\xf0z0)>\xaa^\xc0h\x...,2015-05-28 00:00:00,2015-05-28 00:00:00
1880460,Shasta-Trinity Unit,2015,269,Missing/Undefined,269.0,0.01,A,40.481637,-122.389375,CA,b'\x00\x01\xad\x10\x00\x00P\xb8\x1e\x85\xeb\x9...,2015-09-26 00:00:00,2015-09-26 00:00:00
1880461,Tuolumne-Calaveras Unit,2015,278,Miscellaneous,NaN,0.20,A,37.617619,-120.938570,CA,b'\x00\x01\xad\x10\x00\x00\x00\x80\xbe\x88\x11...,2015-10-05 00:00:00,None
1880462,Tuolumne-Calaveras Unit,2015,122,Missing/Undefined,NaN,0.10,A,37.617619,-120.938570,CA,b'\x00\x01\xad\x10\x00\x00\x00\x80\xbe\x88\x11...,2015-05-02 00:00:00,None
1880463,Tuolumne-Calaveras Unit,2015,287,Missing/Undefined,NaN,2.00,B,37.672235,-120.898356,CA,b'\x00\x01\xad\x10\x00\x00x\xba_\xaa~9^\xc0\xb...,2015-10-14 00:00:00,None
1880464,CDF - San Bernardino Unit,2015,73,Miscellaneous,NaN,0.10,A,34.263217,-116.830950,CA,b'\x00\x01\xad\x10\x00\x00\x1c\xa7\xe8H.5]\xc0...,2015-03-14 00:00:00,None